name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          PYTHONPATH=./ pytest  # Adds `src/` to the import path

  train-and-quantize:
    needs: test-suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: PYTHONPATH=. python src/train.py

      - name: Quantize model
        run: PYTHONPATH=. python src/quantize.py

      - name: Evaluate trained model
        run: PYTHONPATH=. python tests/testing.py

      - name: Generate metrics report
        run: PYTHONPATH=. python reporting.py

      - name: Upload metrics.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-metrics
          path: models/metrics.json

      - name: Upload metrics_plot.png as artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics-visual
          path: models/metrics_plot.png


  build-and-test-container:
    needs: train-and-quantize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t linear-reg-app .
      - name: Run Container
        run: docker run linear-reg-app
