name: CI Pipeline

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test-suite:
    name: 🧪 Setup & Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest Unit Tests
        run: PYTHONPATH=./ pytest

  train-and-quantize:
    name: 🎯 Training and Quantize
    needs: test-suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Train Model
        run: PYTHONPATH=. python src/train.py

      - name: Quantize Model
        run: PYTHONPATH=. python src/quantize.py

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.joblib

      - name: Upload quantized model
        uses: actions/upload-artifact@v4
        with:
          name: quantized-model
          path: models/model_quantized.joblib

  qa-check:
    name: ✅ QA
    needs: train-and-quantize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: models

      - name: Download quantized model
        uses: actions/download-artifact@v4
        with:
          name: quantized-model
          path: models

      - name: Run Model Evaluation Tests
        run: PYTHONPATH=. python tests/testing.py

      - name: Generate Evaluation Plot
        run: PYTHONPATH=. python reporting.py

      - name: Upload metrics.json
        uses: actions/upload-artifact@v4
        with:
          name: model-metrics
          path: models/metrics.json

      - name: Upload metrics_plot.png
        uses: actions/upload-artifact@v4
        with:
          name: metrics-visual
          path: models/metrics_plot.png

      - name: Upload quant_metrics.json
        uses: actions/upload-artifact@v4
        with:
          name: quantized-metrics
          path: models/quant_metrics.json

      - name: Upload predictions.json
        uses: actions/upload-artifact@v4
        with:
          name: full-predictions
          path: models/predictions.json

  build-container:
    name: 🔨 Build Container
    needs: qa-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t linear-reg-app .

  test-container:
    name: 🧪 Test Container
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rebuild Docker Image (needed in this job too)
        run: docker build -t linear-reg-app .

      - name: Run Docker Container
        run: docker run linear-reg-app

  uat-stage:
    name: 🧪 UAT
    needs: test-container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: models

      - name: Download quantized model
        uses: actions/download-artifact@v4
        with:
          name: quantized-model
          path: models

      - name: Run Final End-to-End UAT Tests (20 checks)
        run: PYTHONPATH=. python tests/uat_tests.py

  deployment:
    name: 🚀 Deployment (DockerHub)
    needs: uat-stage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Rebuild Docker image
        run: docker build -t linear-reg-app .

      - name: Tag and Push Docker Image
        run: |
          docker tag linear-reg-app ${{ secrets.DOCKER_USERNAME }}/linear-reg-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/linear-reg-app:latest
